---
- name: Stop and disable apache2 if present (node1)
  service:
    name: apache2
    state: stopped
    enabled: false
  ignore_errors: true
  when: inventory_hostname in groups['app']

- name: Stop and disable nginx if present (node1/node2)
  service:
    name: nginx
    state: stopped
    enabled: false
  ignore_errors: true
  when: inventory_hostname in groups['app'] or inventory_hostname in groups['db']
